name: deploy-on-s3
on:
  push:
    branches:
      - main
      - stage
      - dev
        
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/download-artifact@v4
          with:
            name: build
            path: ./build

        # - uses: jakejarvis/s3-sync-action@master
        #   with:
        #     args: --acl public-read --follow-symlinks --delete
        #   env:
        #     AWS_S3_BUCKET: "${{github.head_ref}}-fullstack-challenge"
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        #     SOURCE_DIR: 'build'

