name: Deploy
on: 
  push: 
    branches:
        - main
        - stage
        - devel
        
jobs: 
    Deploy:
        runs-on: ubuntu-altest
        steps: 
            - uses: actions/download-artifact@v4
              with:
                name: build

            - name: List files 
              run: | 
                ls -lah 
                ls -lah build



