name: deploy-on-s3
on:
  push:
    branches:
      - main
      - stage
      - dev
        
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps: 
        - name: display github
          env: 
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"

        - uses: dawidd6/action-download-artifact@v6
          with:
            workflow: build.yml
            name: ${{github.event.number}}
            path: downloaded-artifact
            workflow_conclusion: success
            branch: ${{github.base_ref}}

        - name: list directory
          run: |
            ls -lah
            ls -lah downloaded-artifact
            ls -lah downloaded-artifact/${{github.event.number}}

        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: "dev-fullstack-challenge"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
            SOURCE_DIR: 'downloaded-artifact/${{github.event.number}}'

