name: enforce-naming-convention

on:
  pull_request:
    branches:
      - dev

jobs: 
    check: 
        runs-on: ubuntu-latest
        steps:
            - name: Check name pattern 
              run: | 
                BRANCH="${{github.GITHUB_REF_NAME}}" 
                if [[ ! "$BRANCH" =~ ^(bugfix|feauture)/.+$ ]]; then
                    echo "Error: branch does not match naming convetions"
                    exit 1
                fi
