name: enforce-naming-convention

on:
  pull_request:
    branches:
      - dev

jobs: 
    check: 
        runs-on: ubuntu-latest
        steps:
            - name: display github envs
              env: 
                GITHUB_CONTEXT: "${{github}}"
              run: |
                echo "$GITHUB_CONTEXT"
            - name: Check name pattern
              env: 
                BRANCH: "${{github.ref_name}}" 
              run: | 
                env
                echo "Branch name= $BRANCH"
                if [[ ! "$BRANCH" =~ ^(bugfix|feauture)/.+$ ]]; then
                    echo "Error: branch does not match naming convetions"
                    exit 1
                fi
