name: stage-rule

on:
    pull_request:
        branches:
            - stage

jobs:
    check_pr_source:
        runs-on: ubuntu-latest
        steps:
            - name: display github
              env: 
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                echo "$GITHUB_CONTEXT"

            - name: Fail if pr is not from dev
              if: ${{github.head_ref}} =! 'dev'
              run: |
                echo "Error: you can only merge from 'dev' branch. '${{github.head_ref}}'"
                exit 1
