name: stage-rule

on:
    pull_request:
        branches:
            - stage

jobs:
    check_pr_source:
        runs-on: ubuntu-latest
        steps:
            - name: Fail if pr is not from dev
              if: ${{github.base_ref}} =! "dev"
              run: |
                echo: "Error: you can only merge from 'dev' branch."
                exit 1
